### PR TITLE
VLESS-TCP-TLS-gRPC

### PR DESCRIPTION
**Pull request by CrazyBoyFeng**
带有回落分流功能，仿照 `VLESS-TCP-TLS-WS`  
With fallback feature, like `VLESS-TCP-TLS-WS`

### CODE REVIEW

**Comment by kslr** [comment]
这应该为实现功能的最简单配置

**Comment by CrazyBoyFeng** [comment]
我是仿照 VLESS-TCP-TLS-WS 写的

**Comment by kslr** [comment]
timeout closed

**Comment by CrazyBoyFeng** [comment]
Is there anything wrong with this configuration?

**Pull request closed without merging**
